const ADD_PROJECT = "ADD_PROJECT";
const REMOVE_PROJECT = "REMOVE_PROJECT";
const UPDATE_PROJECT = "UPDATE_PROJECT";
const TOGGLE_PROJECT_DIALOG = "TOGGLE_PROJECT_DIALOG";
const EDIT_PROJECT_ID = "EDIT_PROJECT_ID";
const TOGGLE_PROJECT_FORM = "TOGGLE_PROJECT_FORM";

export {
  ADD_PROJECT,
  REMOVE_PROJECT,
  UPDATE_PROJECT,
  TOGGLE_PROJECT_DIALOG,
  EDIT_PROJECT_ID,
  TOGGLE_PROJECT_FORM,
};
