const ADD_TASK = "ADD_TASK"
const UPDATE_TASK = "UPDATE_TASK"
const REMOVE_TASK = "REMOVE_TASK"
const SEARCH_TASKS = "SEARCH_TASKS"
const CLOSE_TASK_DIALOG = "CLOSE_TASK_DIALOG"
const EDIT_TASK_ID = "EDIT_TASK_ID"
const TOGGLE_TASK_FORM = "TOGGLE_TASK_FORM"
const ACTIVE_CLASS = "ACTIVE_CLASS"
const ADD_TASK_ID = "ADD_TASK_ID"

export {
    ADD_TASK,
    UPDATE_TASK,
    REMOVE_TASK,
    SEARCH_TASKS,
    CLOSE_TASK_DIALOG,
    EDIT_TASK_ID,
    TOGGLE_TASK_FORM,
    ACTIVE_CLASS,
    ADD_TASK_ID
}
